# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 226fc5f219753fc43eef10511d69a61a991a837564cb6673aadaf8bd0f3f420ec27b4256cab4a0ded586670be150d544261543d5e055e8f5e939a1884bbe0cb0

test:
  secret_key_base: f0fb7a5b607e189f94c2526947aa0f02292f526a813c9e5548bf63e27936d4aa6a311ff8d8e467610c2ea32fbf646b0658291eb6ef1560be8d079e2e25b6a5f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
